# Generated by Django 2.2 on 2022-05-01 13:19

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', mdeditor.fields.MDTextField(null=True, verbose_name='首页简介')),
                ('bottom', mdeditor.fields.MDTextField(null=True, verbose_name='网站底部标题')),
                ('about_me', mdeditor.fields.MDTextField(verbose_name='关于我')),
            ],
            options={
                'verbose_name_plural': '欢迎信息，关于我，网站底部信息',
                'db_table': 'about_me',
            },
        ),
        migrations.CreateModel(
            name='LeaveAMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.CharField(max_length=600, verbose_name='留言内容')),
                ('user_id', models.IntegerField(verbose_name='留言用户id')),
            ],
            options={
                'verbose_name_plural': '网站留言',
                'db_table': 'leave_a_message',
            },
        ),
    ]
