# Generated by Django 2.2 on 2022-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePlateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='home_plate/', verbose_name='首页板块封面')),
                ('title', models.CharField(max_length=32, verbose_name='板块标题')),
                ('url', models.URLField(verbose_name='板块url')),
            ],
            options={
                'verbose_name_plural': '首页板块',
                'db_table': 'home_plate',
            },
        ),
        migrations.AlterField(
            model_name='aboutmemodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='leaveamessagemodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
