# Generated by Django 2.2 on 2022-05-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_manage_app', '0003_homeplatemodel_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeplatemodel',
            name='index',
            field=models.PositiveSmallIntegerField(verbose_name='排序号'),
        ),
    ]
