# Generated by Django 2.2 on 2022-05-03 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_manage_app', '0004_auto_20220502_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='BYCInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', mdeditor.fields.MDTextField(null=True, verbose_name='首页简介')),
                ('bottom', mdeditor.fields.MDTextField(null=True, verbose_name='网站底部标题')),
                ('about_me', mdeditor.fields.MDTextField(verbose_name='关于我')),
            ],
            options={
                'verbose_name_plural': '欢迎信息，关于我，网站底部信息',
                'db_table': 'byc_info',
            },
        ),
        migrations.DeleteModel(
            name='AboutMeModel',
        ),
        migrations.RemoveField(
            model_name='leaveamessagemodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='leaveamessagemodel',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
