# Generated by Django 2.2 on 2022-05-03 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_manage_app', '0005_auto_20220503_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveamessagemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
