# Generated by Django 2.2 on 2022-05-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_manage_app', '0006_auto_20220503_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveamessagemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='leaveamessagemodel',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='留言用户id'),
            preserve_default=False,
        ),
    ]
