# Generated by Django 2.2 on 2022-05-03 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_manage_app', '0007_auto_20220503_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveamessagemodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='leaveamessagemodel',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
