# Generated by Django 2.2 on 2022-05-03 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_manage_app', '0008_auto_20220503_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveamessagemodel',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
