# Generated by Django 2.2 on 2022-05-01 13:19

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DzModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', mdeditor.fields.MDTextField(blank=True, verbose_name='内容')),
                ('favour', models.IntegerField(default=0, verbose_name='获赞数')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '搞笑段子',
                'db_table': 'dz',
            },
        ),
    ]
