# Generated by Django 2.2 on 2022-05-14 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fun_time_app', '0002_auto_20220502_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dzmodel',
            name='favour',
        ),
        migrations.RemoveField(
            model_name='dzmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='dzmodel',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
            preserve_default=False,
        ),
    ]
