# Generated by Django 2.2 on 2022-05-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_time_app', '0003_auto_20220514_0050'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dzmodel',
            table='fun_time_dz',
        ),
    ]
