# Generated by Django 2.2 on 2022-05-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20220502_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='icon',
            new_name='avatar',
        ),
    ]
