# Generated by Django 2.2 on 2020-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bbrowse',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览数'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='bfavour',
            field=models.PositiveIntegerField(default=0, verbose_name='获赞数'),
        ),
    ]
