# Generated by Django 2.2 on 2020-08-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_leaveamessagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('username', models.CharField(max_length=30, verbose_name='用户')),
                ('bid', models.IntegerField(verbose_name='文章id')),
            ],
            options={
                'db_table': 'blog_comment',
            },
        ),
    ]
