# Generated by Django 2.2 on 2021-05-23 13:48

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20210523_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodel',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='关于我'),
        ),
    ]
