# Generated by Django 2.2 on 2021-05-23 15:55

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20210523_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmemodel',
            name='jj',
            field=mdeditor.fields.MDTextField(null=True, verbose_name='首页简介'),
        ),
        migrations.AddField(
            model_name='aboutmemodel',
            name='lx',
            field=models.CharField(max_length=100, null=True, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='aboutmemodel',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='网站底部标题'),
        ),
    ]
