# Generated by Django 2.2 on 2022-05-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.URLField(verbose_name='图片url')),
            ],
            options={
                'verbose_name_plural': '电影轮播图',
                'db_table': 'movie_banner',
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('name', models.CharField(max_length=255, verbose_name='电影名')),
                ('time', models.DateField(verbose_name='电影天堂发布此电影时间')),
                ('image', models.CharField(max_length=255, verbose_name='电影封面')),
                ('detail', models.TextField(verbose_name='电影详情')),
                ('url', models.URLField(verbose_name='原电影url')),
            ],
            options={
                'verbose_name_plural': '电影',
                'db_table': 'movie',
            },
        ),
    ]
