# Generated by Django 2.2 on 2022-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20220508_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='time',
            field=models.DateTimeField(verbose_name='电影天堂发布此电影时间'),
        ),
    ]
