# Generated by Django 2.2 on 2022-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_auto_20220508_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='电影封面'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='url',
            field=models.URLField(null=True, verbose_name='原电影url'),
        ),
    ]
