# Generated by Django 2.2 on 2022-05-01 13:19

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.CharField(max_length=600, verbose_name='评论内容')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('blog_id', models.IntegerField(verbose_name='文章id')),
            ],
            options={
                'verbose_name_plural': '文章评论',
                'db_table': 'blog_comment',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=254, verbose_name='文章标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='正文')),
                ('browse', models.IntegerField(default=0, verbose_name='阅读量')),
                ('favour', models.IntegerField(default=0, verbose_name='获赞数')),
                ('comment', models.IntegerField(blank=True, default=0, verbose_name='评论数')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('blog_type_id', models.IntegerField(verbose_name='类型id')),
            ],
            options={
                'verbose_name_plural': '博客',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='BlogTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(max_length=100, verbose_name='文章类型')),
            ],
            options={
                'verbose_name_plural': '文章类型',
                'db_table': 'blog_type',
            },
        ),
    ]
