# Generated by Django 2.2 on 2022-05-03 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0002_auto_20220502_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcommentmodel',
            name='blog_id',
        ),
        migrations.RemoveField(
            model_name='blogcommentmodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_type_id',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='blog',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_app.BlogModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='blog_type',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_app.BlogTypeModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
