# Generated by Django 2.2 on 2022-05-14 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0004_auto_20220506_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFavourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_app.BlogModel', verbose_name='用户点赞的文章')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='点赞的用户')),
            ],
            options={
                'verbose_name_plural': '文章评论',
                'db_table': 'blog_favour',
            },
        ),
    ]
